services:
  pgsql:
    build: .
    restart: no
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: postgres
    ports:
      - 54317:5432
    volumes:
      - .\fs\data:/var/lib/postgresql/data
      - ..\..\scripts\:/home/scripts
      - .\fs\scripts:/home/dockerscripts
